--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/LDFx
build-by-default: true
branches:
- main
projects:
  LDFx:
    path: ""
    icon: ""
    lint: true
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
      - src: BladeNetwork-MC/apibossbar/apibossbar
        version: ^0.1.5
        branch: PM4
...
