name: LDFx
version: 2.3
main: LDFx\ItsToxicGG\LDFx
author: ItsToxicGG
api: 4.0.0

permissions:
  settings.fx:
    description: "/settings" 
    default: op
  fly.fx:
    description: "/fly"
    default: op   
  nickcolor.fx:
    description: "/nickcolor"
    default: op
  nicknames.fx:
    description: "/nickname"
    default: op
  maintenace.fx:
    description: "/maintenace"
    default: op
  bypassmaintenace.fx:
    description: "bypass maintenace, for staff, mods, etc."
    default: op
  
